"""
Django settings for rematch project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qvc7t@rd5#1l-n_%%&+_fu+-lu#sp2oonf9mto%bn-1#i7$(tu'

# SECURITY WARNING: don't run with debug turned on in production!
# FIXME
if "celeryd" in sys.argv or "celery" in sys.argv:
  DEBUG = False
else:
  DEBUG = True


# As of django 1.10, allowed hosts are validated in debug as well,
# this disables that and makes sure all hosts are acceptible when
# running in debug mode. for more details see
# https://docs.djangoproject.com/en/1.10/ref/settings/
# for security implications see
# https://docs.djangoproject.com/en/1.10/topics/security/ \
# #host-headers-virtual-hosting
if DEBUG:
  ALLOWED_HOSTS = ['*']
else:
  ALLOWED_HOSTS = ['127.0.0.1', '172.18.0.*', '192*']


# Application definition

INSTALLED_APPS = [
    'accounts',
    'collab',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'djcelery',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rematch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rematch.wsgi.application'


# Django rest framework configuration
REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework.authentication.BasicAuthentication',
    'rest_framework.authentication.TokenAuthentication',
    'rest_framework.authentication.SessionAuthentication',
  ),

  'DEFAULT_FILTER_BACKENDS': (
    'django_filters.rest_framework.DjangoFilterBackend',
  ),

  'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination'
}

REST_SESSION_LOGIN = False

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rematch',
        'USER': 'root',
        'PASSWORD': 'qwe123',
        'HOST': 'db0_1',
        'PORT': 3306,
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES';",
        },
    }
}

# in case we're not in docker we have all the environment
# locally, unless someone specified something else.
# this condition is for Travis and other code
# analysis systems
indocker = os.environ.get('IN_DOCKER')
if indocker is None:
  DATABASES['default'].pop('HOST')
  DATABASES['default'].pop('PASSWORD')
  DATABASES['default'].pop('PORT')

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static/")

# Celery configuration
CELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


if os.environ.get('IN_DOCKER') is not None:
 
  # docker conf
  REDIS_PORT = 6379
  REDIS_DB = 0
  REDIS_HOST = os.environ.get('REDIS_PORT_6379_TCP_ADDR', 'redis_1')

  RABBIT_HOSTNAME = os.environ.get('RABBIT_PORT_5672_TCP', 'rabbitmq_1')

  if RABBIT_HOSTNAME.startswith('tcp://'):
      RABBIT_HOSTNAME = RABBIT_HOSTNAME.split('//')[1]

  BROKER_URL = os.environ.get('BROKER_URL',
                              '')
  if not BROKER_URL:
      BROKER_URL = 'amqp://{user}:{password}@{hostname}/{vhost}/'.format(
          user=os.environ.get('RABBIT_ENV_USER', 'admin'),
          password=os.environ.get('RABBIT_ENV_RABBITMQ_PASS', 'mypass'),
          hostname=RABBIT_HOSTNAME,
          vhost=os.environ.get('RABBIT_ENV_VHOST', ''))

  # We don't want to have dead connections stored on rabbitmq
  # , so we have to negotiate using heartbeats
  # BROKER_HEARTBEAT = '?heartbeat=30'
  # if not BROKER_URL.endswith(BROKER_HEARTBEAT):
  #    BROKER_URL += BROKER_HEARTBEAT

  BROKER_POOL_LIMIT = 1
  BROKER_CONNECTION_TIMEOUT = 10

  # Celery configuration

  # configure queues, currently we have only one
  # CELERY_DEFAULT_QUEUE = 'default'
  # CELERY_QUEUES = (
  #    Queue('default', Exchange('default'), routing_key='default'),
  # )

  # Sensible settings for celery
  CELERY_ALWAYS_EAGER = False
  CELERY_ACKS_LATE = True
  CELERY_TASK_PUBLISH_RETRY = True
  CELERY_DISABLE_RATE_LIMITS = False

  # By default we will ignore result
  # If you want to see results and try out tasks interactively,
  # change it to False
  # Or change this setting on tasks level
  CELERY_IGNORE_RESULT = True
  CELERY_SEND_TASK_ERROR_EMAILS = False
  CELERY_TASK_RESULT_EXPIRES = 600

  # Set redis as celery result backend
  # CELERY_RESULT_BACKEND = 'redis://%s:%d/%d'\
  #  %(REDIS_HOST, REDIS_PORT, REDIS_DB)
  CELERY_REDIS_MAX_CONNECTIONS = 1

  # Don't use pickle as serializer, json is much safer
  CELERY_TASK_SERIALIZER = "json"
  CELERY_ACCEPT_CONTENT = ['application/json']

  CELERYD_HIJACK_ROOT_LOGGER = False
  CELERYD_PREFETCH_MULTIPLIER = 1
  CELERYD_MAX_TASKS_PER_CHILD = 1000
