# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 20:13
from __future__ import unicode_literals

import collab.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('offset', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('md5hash', models.CharField(db_index=True, max_length=32, validators=[django.core.validators.MinLengthValidator(32)])),
                ('file', models.FileField(null=True, upload_to=b'tasks', validators=[collab.validators.IdbValidator])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'empty_data', b'Empty Data'), (b'data', b'Data'), (b'empty_function', b'Empty Function'), (b'function', b'Function')], max_length=16)),
                ('offset', models.BigIntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='collab.File')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('private', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'hash', b'Hash'), (b'opcode_histogram', b'Opcode Histogram')], max_length=16)),
                ('type_version', models.IntegerField()),
                ('data', models.TextField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='collab.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='AboveLineCommentAnnotation',
            fields=[
                ('annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collab.Annotation')),
                ('comment', models.TextField()),
            ],
            bases=('collab.annotation',),
        ),
        migrations.CreateModel(
            name='BelowLineCommentAnnotation',
            fields=[
                ('annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collab.Annotation')),
                ('comment', models.TextField()),
            ],
            bases=('collab.annotation',),
        ),
        migrations.CreateModel(
            name='CommentAnnotation',
            fields=[
                ('annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collab.Annotation')),
                ('comment', models.TextField()),
            ],
            bases=('collab.annotation',),
        ),
        migrations.CreateModel(
            name='NameAnnotation',
            fields=[
                ('annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collab.Annotation')),
                ('name', models.CharField(max_length=256)),
            ],
            bases=('collab.annotation',),
        ),
        migrations.CreateModel(
            name='RptCommentAnnotation',
            fields=[
                ('annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collab.Annotation')),
                ('comment', models.TextField()),
            ],
            bases=('collab.annotation',),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='collab.Project'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.Instance'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
