# Generated by Django 2.1.2 on 2018-11-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_auto_20181104_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='local_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='match_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='remote_count',
            field=models.IntegerField(default=0),
        ),
    ]
