"""
Django settings for rematch project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from rematch.settings.base import *  # noqa
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Accept all hosts by default, this isn't the most secure
ALLOWED_HOSTS = ['*']  # TODO: this should be your hostname


STATIC_ROOT = "/rematch_server/server/static/"
