"""
Django settings for rematch project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from rematch.settings.base import *  # noqa
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEBUG = False


# Accept all hosts by default, this isn't the most secure
ALLOWED_HOSTS = ['*']  # TODO: this should be your hostname


STATIC_ROOT = "/rematch_server/server/static/"


# rabbitmq configuration
if 'BROKER_URL' in os.environ:
    BROKER_URL = os.environ['BROKER_URL']
else:
    BROKER_URL = 'amqp://{user}:{password}@{host}:{port}/{vhost}'.format(
        user=os.environ['RABBITMQ_USER'],
        password=os.environ['RABBITMQ_PASSWORD'],
        host=os.environ['RABBITMQ_HOST'],
        port=os.environ.get('RABBITMQ_PORT', 5672),
        vhost=os.environ.get('RABBITMQ_VHOST', ''))


# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/log/rematch/django.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
